### ISSUE TITLE
Error during perfstatbeat execution on AIX 7.1

### ISSUE THREAD

**Issue by c01362** [WuerthIT/perfstatbeat#1]
Hello all.

We're trying to install https://github.com/WuerthIT/perfstatbeat on an AIX 7.1 server per the request of our Unix engineering team. 

I'm not familiar with perfbeatstat but was able to build the executable. 

However, when I run it, I get the following error:

./perfstatbeat -e -v -d "*"

2019-04-12T17:07:18.008-0500 
INFO instance/beat.go:468 Home path: [/opt/Tanium/Tom/perfstatbeat/dist] Config path: [/opt/Tanium/Tom/perfstatbeat/dist] Data path: [/opt/Tanium/Tom/perfstatbeat/dist/data] Logs path: [/opt/Tanium/Tom/perfstatbeat/dist/logs] 2019-04-12T17:07:18.009-0500 
DEBUG [beat] instance/beat.go:495 Beat metadata path: /opt/Tanium/Tom/perfstatbeat/dist/data/meta.json 2019-04-12T17:07:18.009-0500 
INFO instance/beat.go:475 Beat UUID: e041363a-717f-4bd1-b046-7be3ec876006 2019-04-12T17:07:18.009-0500 
INFO instance/beat.go:213 Setup Beat: perfstatbeat; Version: 6.2.4 2019-04-12T17:07:18.009-0500 
WARN instance/metrics_other.go:12 Metrics not implemented for this OS. 2019-04-12T17:07:18.009-0500 
DEBUG [beat] instance/beat.go:230 Initializing output plugins 2019-04-12T17:07:18.010-0500 
DEBUG [processors] processors/processor.go:49 Processors: 2019-04-12T17:07:18.010-0500 
INFO pipeline/module.go:91 No outputs are defined. Please define one under the output section. 2019-04-12T17:07:18.010-0500 
**ERROR instance/beat.go:667 Exiting: error initializing publisher: No outputs are defined. Please define one under the output section. Exiting: error initializing publisher: No outputs are defined. Please define one under the output section.**

Where are the outputs mentioned in the ERROR defined?

I looked in the filebeat.yml and found an output section as shown here:

#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

But I'm not clear on what I need to add/edit.

Any suggestions on how to address this?

Please advise.

Thanks all.

**Comment by inxonic** [comment]
Hi c01362,

the config file syntax is very sensitive to whitespace and your copy of it is somewhat distorted by the automatic formatting, so unfortunately I cannot check it by this.

In general you need to setup an output, and probably your Elasticsearch is not running on the same node, you'd need to point the output to that host.

Daniel

**Comment by inxonic** [comment]
Maybe you also have a look at [this](https://discuss.elastic.co/t/no-outputs-are-defined-please-define-one-under-the-output-section/38626). The output configuration is complete handled by upstream code, there is nothing special for perfstatbeat in it.

**Comment by inxonic** [comment]
I'll close this one as I think this is a configuration problem general to Metricbeat and not specific to perfstatbeat.

**Comment by c01362** [comment]
Hello.
Thanks for the feedback.
Yes, please close this thread.
Looks to be unrelated to pertstatbeat.
We're working on the configuration.
